--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: famousapp
  name: famousapp-dpl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: famousapp
  template: 
    metadata: 
      labels: 
        app: famousapp
    spec: 
      containers: 
        - 
          image: "dgtlkrm/famousapp:latest"
          name: nodeserver
          ports: 
            - 
              containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: famousapp-svc
spec:
  selector:
    app: famousapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110